# Generated by Django 6.0.5 on 2026-05-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='real_a_score',
            new_name='score_a',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='real_b_score',
            new_name='score_b',
        ),
        migrations.AlterField(
            model_name='match',
            name='api_match_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
