# Generated by Django 6.0.5 on 2026-05-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_rename_predicted_a_prediction_predicted_team_a_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='logo_a',
            field=models.CharField(default='default.png', max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='logo_b',
            field=models.CharField(default='default.png', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='prediction',
            unique_together={('username', 'match')},
        ),
    ]
