# Generated by Django 6.0.5 on 2026-05-21 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0004_match_logo_a_match_logo_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_finished',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='match',
            name='score_a',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='score_b',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
